
name: Create_Artifacts

# Controls when the action will run. 
on:
  schedule:
    # Every day at 23:00
    - cron:  '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Runs the .py script that generates the json files
      - name: Executing Python script to generate JSON content
        run: python ./main.py
      
      # Commiting to target repos

